### ISSUE TITLE
多次调用内存会飙升

### ISSUE THREAD

**Issue by choujayyl** [kevinlq/QtPythonDocx#1]
内存会泄漏

**Comment by choujayyl** [comment]
测试发现内存飙升，以为泄漏。但是python内存机制。所以需要释放对象，
并且手动调用内存回收。
    Py_CLEAR(pFunObj);
    Py_CLEAR(pArgsObj);
    Py_CLEAR(pReturnObj);
    PyGC_Collect();
测试调用后内存，一直保持不变

**Comment by kevinlq** [comment]
> 测试发现内存飙升，以为泄漏。但是python内存机制。所以需要释放对象， 并且手动调用内存回收。 Py_CLEAR(pFunObj); Py_CLEAR(pArgsObj); Py_CLEAR(pReturnObj); PyGC_Collect(); 测试调用后内存，一直保持不变

这个我到没有注意到，你方便可以把修改后的代码push上来，同步下
