### ISSUE TITLE
VS2015导入该项目，插入图片的部分运行出现了问题，PyObject_CallObject 回调函数返回值变成了空

### ISSUE THREAD

**Issue by conf-haolee** [kevinlq/QtPythonDocx#2]
QtCreator 运行该项目正常，vs仅仅在插入图片部分出现了错误，请问可能是什么原因？
![image](https://github.com/kevinlq/QtPythonDocx/assets/55752542/830e66c1-5958-4a99-bfc6-ae62f0af75b8)
![image](https://github.com/kevinlq/QtPythonDocx/assets/55752542/f7c756fe-fc86-4956-9e09-9f5a6e244754)

**Comment by kevinlq** [comment]
返回为空，99%原因是传入的参数有问题，编码/格式问题。

可以这样检查：
1. 使用示例的程序中定义的结构体，把你要生成的数据转为JSON 后本地保存；
2. 使用上述保存的 JSON 文件，手动调用 Python 进行加载，查看执行过程，如果方便有相关Python 开发环境，直接调试即可；
3. 如果有问题，可以看到到底是那个字段出现问题了

> 具体如何手动调用，可以看这个文件wordOperate.py 最后两个测试方法

```
# 测试
#inputFile = open('test.json', encoding='utf-8')
#exportData = json.loads(inputFile.read())
#generateWord(json.dumps(exportData))
```

以上，如果还有问题，可以提供你的测试工程Demo， 我当时用2015也跑过，没有问题。

**Comment by conf-haolee** [comment]
解决了，图片使用绝对地址，按照 这样的路径格式`  "D:\\title.png" ` 就可以了
或者 使用相对地址 先退到当前目录上一级方式  ` "..\\bin\\title.png"  `
感谢！
